from __future__ import annotations


COMMERCIAL_AGENT_ROLE = "Commercial Agent"
COMMERCIAL_AGENT_PARTNER_ROLE = "Commercial Agent - Partner"
COMMERCIAL_AGENT_COORDINATOR_ROLE = "Commercial Agent - Coordinator"
COMMERCIAL_AGENT_POINT_OF_SALE_ROLE = "Commercial Agent - Point of Sale"

FUNCTIONAL_STARTUP_ROLES = [
    "Orderlift Executive",
    "Sales Distribution Manager",
    "Sales Installation Manager",
    COMMERCIAL_AGENT_ROLE,
    COMMERCIAL_AGENT_PARTNER_ROLE,
    COMMERCIAL_AGENT_COORDINATOR_ROLE,
    COMMERCIAL_AGENT_POINT_OF_SALE_ROLE,
    "Purchase Manager",
    "Stock Manager",
    "Project Manager",
    "Pricing Import Manager",
    "Logistics Manager",
    "BET Technical User",
    "Finance Admin",
    "HR Training Manager",
]

QUOTATION_CREATOR_ROLE = "Quotation Creator"
OPPORTUNITY_ASSIGNER_ROLE = "Opportunity Assigner"
OPPORTUNITY_ALL_ACCESS_ROLE = "Opportunity All Access"
STOCK_QUANTITY_VIEWER_ROLE = "Stock Quantity Viewer"
ITEM_MASTER_EDITOR_ROLE = "Item Master Editor"
AGENT_PRICING_MANAGER_ROLE = "Agent Pricing Manager"
COMMISSION_MANAGER_ROLE = "Commission Manager"
PAYMENT_VALIDATOR_ROLE = "Payment Validator"
CAMPAIGN_MANAGER_ROLE = "Campaign Manager"
DASHBOARD_MANAGER_ROLE = "Dashboard Manager"

CAPABILITY_STARTUP_ROLES = [
    QUOTATION_CREATOR_ROLE,
    OPPORTUNITY_ASSIGNER_ROLE,
    OPPORTUNITY_ALL_ACCESS_ROLE,
    STOCK_QUANTITY_VIEWER_ROLE,
    ITEM_MASTER_EDITOR_ROLE,
    AGENT_PRICING_MANAGER_ROLE,
    COMMISSION_MANAGER_ROLE,
    PAYMENT_VALIDATOR_ROLE,
    CAMPAIGN_MANAGER_ROLE,
    DASHBOARD_MANAGER_ROLE,
]

STARTUP_ROLES = FUNCTIONAL_STARTUP_ROLES + CAPABILITY_STARTUP_ROLES
COMMERCIAL_STARTUP_ROLES = [
    COMMERCIAL_AGENT_ROLE,
    COMMERCIAL_AGENT_PARTNER_ROLE,
    COMMERCIAL_AGENT_COORDINATOR_ROLE,
    COMMERCIAL_AGENT_POINT_OF_SALE_ROLE,
]
RESTRICTED_COMMERCIAL_ROLES = set(COMMERCIAL_STARTUP_ROLES) | {"Sales User", "Orderlift Commercial"}
QUOTATION_CAPABLE_COMMERCIAL_ROLES = set(COMMERCIAL_STARTUP_ROLES) | {QUOTATION_CREATOR_ROLE}
